# Generated by Django 6.0.4 on 2026-05-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
