# Generated by Django 6.0.4 on 2026-04-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_price_order_payment_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
